# Generated by Django 5.0 on 2024-05-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileModel', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('img', models.BinaryField(blank=True, null=True)),
                ('author_name', models.CharField(max_length=50)),
                ('about_author', models.TextField()),
                ('category', models.CharField(default='no category', max_length=50, null=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('trending_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileModel.profilemodel')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
