# Generated by Django 5.0.6 on 2024-05-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
